# docker-compose.yml
version: '3.8'

services:
  # 1. Base de Datos PostgreSQL
  ferreteria_db:
    image: postgres:15
    container_name: ferreteria_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123 # Pon tu contraseña real
      POSTGRES_DB: ferrosoft_bd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always # Se inicia solo al prender la PC

  # 2. Servidor WebSocket
  websocket_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ferreteria_ws
    ports:
      - "8765:8765"
    depends_on:
      - ferreteria_db
    restart: always # Se inicia solo al prender la PC

# Volumen para que la base de datos no se borre si apagas el contenedor
volumes:
  pgdata: